@base = http://localhost:3000

###
GET {{base}}/users HTTP/1.1

###

GET {{base}}/users/1

###

POST {{base}}/users HTTP/1.1
Content-Type: application/json

{
    "name":"Name",
    "age":18
}

###

DELETE {{base}}/users/6 HTTP/1.1
