@base = http://localhost:3000

###
GET {{base}}/users HTTP/1.1

###

GET {{base}}/users/1

###

POST {{base}}/users HTTP/1.1
Content-Type: application/json

{
    "name":"Plazeba",
    "email":"dota2gembitlox67@gmail.com",
    "password":"ppfknehodjy"
}

###

DELETE {{base}}/users/3 HTTP/1.1
